import '../models/model.dart';

List<ProductModel> beerList = [
  ProductModel (
   //  id:0,
      name: "Bira 1",
      img: "assets/images/antonio_rose.jpg",
      description: "Description1",
      firstStep: "bira1 step1 1",
      secondStep: "bira1 step2 1",
      ingredient: "Ingredient1 Ingredient2"),
  ProductModel(
   // id: 1,
      name: "Bira 2",
      img: "assets/images/isabella_mendes.jpg",
      description: "Description2",
      firstStep: "bira2 step1",
      secondStep: "bira2 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3"),
  ProductModel(
   // id: 2,
      name: "Bira 3",
      img: "assets/images/martini_drink.jpg",
      description: "Description3",
      firstStep: "bira3 step1",
      secondStep: "bira2 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3"),
  ProductModel(
   // id: 3,
      name: "Bira 4",
      img: "assets/images/valeria.jpg",
      description: "Description4",
      firstStep: "bira4 step1",
      secondStep: "bira2 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 4,
      name: "Bira 5",
      img: "assets/images/antonio_rose.jpg",
      description: "Description5",
      firstStep: "bira5 step1",
      secondStep: "bira5 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3"),
  ProductModel(
  //  id: 5,
      name: "Bira 6",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "bira6 step1",
      secondStep: "bira6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
    //  id: 5,
      name: "Bira 7",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "bira6 step1",
      secondStep: "bira6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
    //  id: 5,
      name: "Bira 8",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "bira6 step1",
      secondStep: "bira6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
];


List<ProductModel> liqueurList = [
  ProductModel(
   // id: 0,
      name: "Likör 1",
      img: "assets/images/antonio_rose.jpg",
      description: "Description1",
      firstStep: "Likör 1 step1",
      secondStep: "Likör1 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 1,
      name: "Likör 2",
      img: "assets/images/isabella_mendes.jpg",
      description: "Description2",
      firstStep: "Likör 2 step1",
      secondStep: "Likör2 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3"),
  ProductModel(
   // id: 2,
      name: "Likör 3",
      img: "assets/images/martini_drink.jpg",
      description: "Description3",
      firstStep: "Likör 3 step1",
      secondStep: "Likör3 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 3,
      name: "Likör 4",
      img: "assets/images/valeria.jpg",
      description: "Description4",
      firstStep: "Likör 4 step1",
      secondStep: "Likör4 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 4,
      name: "Likör 5",
      img: "assets/images/antonio_rose.jpg",
      description: "Description5",
      firstStep: "Likör 5 step1",
      secondStep: "Likör5 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3"),
  ProductModel(
   // id: 5,
      name: "Likör 6",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Likör 6 step1",
      secondStep: "Likör6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
    // id: 5,
      name: "Likör 7",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Likör 6 step1",
      secondStep: "Likör6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
    // id: 5,
      name: "Likör 8",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Likör 6 step1",
      secondStep: "Likör6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
];

List<ProductModel> tequilaList = [
  ProductModel(
   // id: 0,
      name: "Tekila 1",
      img: "assets/images/antonio_rose.jpg",
      description: "Description1",
      firstStep: "Tekila1 Step1",
      secondStep: "Tekila1 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 1,
      name: "Tekila 2",
      img: "assets/images/isabella_mendes.jpg",
      description: "Description2",
      firstStep: "Tekila2 Step1",
      secondStep: "Tekila2 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 2,
      name: "Tekila 3",
      img: "assets/images/martini_drink.jpg",
      description: "Description3",
      firstStep: "Tekila3 Step1",
      secondStep: "Tekila3 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 3,
      name: "Tekila 4",
      img: "assets/images/valeria.jpg",
      description: "Description4",
      firstStep: "Tekila4 Step1",
      secondStep: "Tekila4 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 4,
      name: "Tekila 5",
      img: "assets/images/antonio_rose.jpg",
      description: "Description5",
      firstStep: "Tekila5 Step1",
      secondStep: "Tekila5 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3"),
  ProductModel(
   // id: 5,
      name: "Tekila 6",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Tekila6 Step1",
      secondStep: "Tekila6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
    // id: 5,
      name: "Tekila 7",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Tekila6 Step1",
      secondStep: "Tekila6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
    // id: 5,
      name: "Tekila 8",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Tekila6 Step1",
      secondStep: "Tekila6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
];

List<ProductModel> whiskeyList = [
  ProductModel(
  //  id: 0,
      name: "Viski 1",
      img: "assets/images/antonio_rose.jpg",
      description: "Description1",
      firstStep: "Viski1 Step1",
      secondStep: "Viski1 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 1,
      name: "Viski 2",
      img: "assets/images/isabella_mendes.jpg",
      description: "Description2",
      firstStep: "Viski2 Step1",
      secondStep: "Viski2 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 2,
      name: "Viski 3",
      img: "assets/images/martini_drink.jpg",
      description: "Description3",
      firstStep: "Viski3 Step1",
      secondStep: "Viski3 step2",
      ingredient: "Ingredient1 Ingredient2"),
  ProductModel(
  //  id: 3,
      name: "Viski 4",
      img: "assets/images/valeria.jpg",
      description: "Description4",
      firstStep: "Viski4 Step1",
      secondStep: "Viski4 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3"),
  ProductModel(
   // id: 4,
      name: "Viski 5",
      img: "assets/images/antonio_rose.jpg",
      description: "Description5",
      firstStep: "Viski5 Step1",
      secondStep: "Viski5 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 5,
      name: "Viski 6",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Viski6 Step1",
      secondStep: "Viski6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
    // id: 5,
      name: "Viski 7",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Viski6 Step1",
      secondStep: "Viski6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
    // id: 5,
      name: "Viski 8",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Viski6 Step1",
      secondStep: "Viski6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
];

List<ProductModel> wineList = [
  ProductModel(
 //   id: 0,
      name: "Şarap 1",
      img: "assets/images/antonio_rose.jpg",
      description: "Description1",
      firstStep: "Şarap1 Step1",
      secondStep: "Şarap1 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 1,
      name: "Şarap 2",
      img: "assets/images/isabella_mendes.jpg",
      description: "Description2",
      firstStep: "Şarap2 Step1",
      secondStep: "Şarap2 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 2,
      name: "Şarap 3",
      img: "assets/images/martini_drink.jpg",
      description: "Description3",
      firstStep: "Şarap3 Step1",
      secondStep: "Şarap3 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
  //  id: 3,
      name: "Şarap 4",
      img: "assets/images/valeria.jpg",
      description: "Description4",
      firstStep: "Şarap4 Step1",
      secondStep: "Şarap4 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
  //  id: 4,
      name: "Şarap 5",
      img: "assets/images/antonio_rose.jpg",
      description: "Description5",
      firstStep: "Şarap5 Step1",
      secondStep: "Şarap5 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
   // id: 5,
      name: "Şarap 6",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Şarap6 Step1",
      secondStep: "Şarap6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
    // id: 5,
      name: "Şarap 7",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Şarap6 Step1",
      secondStep: "Şarap6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
  ProductModel(
    // id: 5,
      name: "Şarap 8",
      img: "assets/images/antonio_rose.jpg",
      description: "Description6",
      firstStep: "Şarap6 Step1",
      secondStep: "Şarap6 step2",
      ingredient: "Ingredient1 Ingredient2 Ingredient3 Ingredient4"),
];
