import 'package:cocktail_app/models/model.dart';

List<ProductModel> coffeeCocktails = [
  ProductModel(
      id: 1000,
      name: "Espresso Martini",
      img: "assets/images/coffee_cocktails_img/espresso_martini_coffee.jpg",
      description: "Alkollü içecek - Votka",
      firstStep: "Buzla doldurulmuş bir çalkalayıcıya votka, kahve likörü, espresso ve basit şurubu ekleyin ve iyice soğuyuncaya kadar çalkalayın.",
      secondStep: "Soğutulmuş bir kokteyl bardağına süzün. 3 kahve çekirdeği ile süsleyin.",
      ingredient: "60 ml Votka,15 ml kahve likörü,30 ml espresso,7 ml şeker şurubu,Kahve çekirdekleri"),
  ProductModel(
      id: 1001,
      name: "İrlanda Kahvesi",
      img: "assets/images/coffee_cocktails_img/irish_coffee.jpg",
      description: "Alkollü içecek - Viski",
      firstStep:"Bir İrlanda Kahvesi kupasını sıcak suyla doldurun, 2 dakika bekletin ve ardından suyu dökün.",
      secondStep: "Isıtılmış bardağa viski ve şekeri ekleyin, kahveyi doldurun ve karıştırın. Üstüne şekersiz, hafif çırpılmış krema ekleyin.",
      ingredient: "30 ml İrlanda viskisi,2 çay kaşığı esmer şeker,Sıcak demlenmiş kahve,Krem şanti"),
  ProductModel(
      id: 1002,
      name: "İrlanda Affogato",
      img: "assets/images/coffee_cocktails_img/irish_affogato_coffee.jpg",
      description: "Alkollü içecek - Viski",
      firstStep:"*Soğuk demlenmiş kahve: En sevdiğiniz şişelenmiş soğuk demlenmiş kahveyi kullanın veya 140 gram kaba öğütülmüş kahve çekirdeklerini 32 ons su ile 12 saat boyunca ıslatarak kendiniz yapın. Demlendikten sonra kahve filtresinden geçirerek temiz bir kavanoza alın. Katıları atın. Soğuk demlemeyi buzdolabında birkaç gün saklayın.",
      secondStep: "İrlanda Kahvesi kupasına İrlanda viskisi, Baileys İrlanda kreması, kahveli dondurma ve soğuk demlenmiş kahve ekleyin. Krem şanti ve çikolata parçacıklarıyla süsleyin.",
      ingredient: "24 ml İrlanda viskisi,15 ml krema,1 top kahveli dondurma,30 ml demlenmiş kahve*,Krem şanti,Çikolata parçacıkları"),
  ProductModel(
      id: 1003,
      name: "Beyaz Rus",
      img: "assets/images/coffee_cocktails_img/white_russian_coffee.jpg",
      description: "Alkollü içecek - Votka",
      firstStep:"Bardağa buz doldurun. Votka ve kahve likörünü bir bardağa ekleyin. Üzerine kremayı dökün. Girdap efekti elde etmek için yavaşça karıştırın. Beyaz bir Rus'u kuvvetlice karıştırdığınızda bej renkli bir içecek elde edersiniz.",
      secondStep: "Krema alternatifi:\nSüt: Süt, kremaya göre daha sulu, daha az incelikli bir içecek yapar. Ancak o kadar zengin olmadığı ve kaloriyi azalttığı için bu kokteylin içimini kolaylaştırıyor. Yalnızca tam yağlı süt veya %2 kullanın (burada az yağlı veya yağsız sütten kaçının).",
      ingredient: "60 ml votka,30 ml kahve likörü,30 ml krema,Buz"),
  ProductModel(
      id: 1004,
      name: "Siyah Rus",
      img: "assets/images/coffee_cocktails_img/black_russian_coffee.jpg",
      description: "Alkollü içecek - Rom",
      firstStep:"Malzemelerinizi aldıktan sonra, bu iki malzemeli kokteylin hazırlanması yalnızca birkaç dakika sürer. Beyaz Rus'tan bir farkı var: Malzemeleri bardakta karıştırmıyorsunuz. Bunun yerine, bunları bir karıştırma bardağında karıştırın.",
      secondStep: "Buz ile çalkalanıp farklı bir bardağa aktarılmalıdır.",
      ingredient: "60 ml votka,30 ml kahve likörü"),
  ProductModel(
      id: 1005,
      name: "Coffee Martini",
      img: "assets/images/coffee_cocktails_img/coffee_martini.jpg",
      description: "Alkollü içecek - Votka\nCoffee Martini, kahveyle yapılan bir votka martinidir ve Espresso Martini'den farklıdır. Espresso Martini, 1980'lerde icat edilen, espresso, votka ve Kahlua ile yapılan klasik bir kokteyldir. Bu Coffee Martini, İrlanda kremasının zengin kremsi yapısını geleneksel votka ve Kahlua kombinasyonuyla birleştiriyor.",
      firstStep:"Kokteyl bardağının kenarını ıslatın. İnce öğütülmüş kahve çekirdeklerini ve şekeri bir tabağa yerleştirin ve bardağın dış kenarını batırın.",
      secondStep: "Kahveyi, votkayı, Kahlua'yı ve İrlanda kremasını bir kokteyl çalkalayıcıya koyun. 2 avuç buz ekleyin ve soğuyuncaya kadar çalkalayın. Hazırlanan kokteyl bardağına süzün.",
      ingredient: "60 ml demlenmiş kahve,30 ml votka,15 ml kahve likörü,15 ml İrlanda kreması,Kahve çekirdekleri ve şeker"),
  ProductModel(
      id: 1006,
      name: "Carajillo",
      img: "assets/images/coffee_cocktails_img/carajillo_coffee.jpg",
      description: "Alkollü içecek - Likör",
      firstStep:"Espresso yapın.Bardağa buz ekleyin. Licor 43'ü ekleyin ve karıştırın.",
      secondStep: "Kahveyi yavaşça içeceğe dökün, içecek üstüne çöksün. Derhal servis yapın.",
      ingredient: "60 ml espresso,30 ml Likör 43,Servis için Buz"),
  ProductModel(
      id: 1007,
      name: "Tiramisu white russians",
      img: "assets/images/coffee_cocktails_img/tiramisu_white_russians_coffee.jpg",
      description: "Alkollü içecek - Rom",
      firstStep:"Yarım litrelik bir cam kavanoza krema ve şekeri ekleyin, kapatın ve krema, yaklaşık 3 dakika kadar yumuşak bir tepe noktası tutacak kadar kalınlaşana kadar kuvvetlice çalkalayın. (Alternatif olarak, kremayı çırpmak için bir çırpma teli veya el mikseri ve büyük bir kase kullanın.)",
      secondStep: "2 bardağı buzla doldurun. Her bardağa 60 ml Kahlua(kahve likörü) ve 60 ml rom ekleyin ve birleştirmek için karıştırın. Ardından, bir kaşık kullanarak çırpılmış kremayı bardakların arasına eşit şekilde bölün ve kaşığın arkasını kullanarak içeceğin yüzeyini kaplayacak şekilde düz bir tabaka haline getirin. Üstlerine kakao tozu serpin, kurabiye yarısıyla süsleyin ve servis yapın.",
      ingredient: "115 gram soğuk krema,2 çay kaşığı toz şeker,Buz,115 ml Kahlua(kahve likörü),115 ml koyu rom,Süslemek için kakao tozu,1 kedi dili kurabiyesi"),
  ProductModel(
      id: 1008,
      name: "Toprak kayması",
      img: "assets/images/coffee_cocktails_img/mudslide_coffee.webp",
      description: "Alkollü içecek - Votka - Likör",
      firstStep:"İki kokteyl bardağının içine çikolata sosunu içinde gezdirerek şekiller verin.",
      secondStep: "Kokteyl çalkalayıcıya votka, Kahlua, Baileys ve ağır kremayı ekleyin. Buzla doldurun ve iyice soğuyana kadar çalkalayın. Bardaklara süzün ve çikolata parçacıklarıyla süsleyin.",
      ingredient: "Çikolata sosu(bardak için),115 ml votka,60 ml kahve likörü,60 ml Baileys,1/4 bardak yoğun krema,Çikolata parçacıkları"),
  ProductModel(
      id: 1009,
      name: "Soğuk Brew Sangria",
      img: "assets/images/coffee_cocktails_img/cold_brew_sangria_coffee.jpg",
      description: "Alkollü içecek - Tekila - Portakal likörü",
      firstStep:"Soğuk demleme, tekila, portakal likörü ve basit şurubu büyük bir sürahide birleştirin ve iyice karışana kadar karıştırın.",
      secondStep: "Meyve ekleyin ve 30 dakika ila 1 saat arasında buzdolabında saklayın. Buzla doldurulmuş bardaklara dökün ve servis yapın.",
      ingredient: "950 ml soğuk demleme kahve,230 ml tekila,115 ml portakal aromalı likör, 1 yemek kaşığı basit şurup, 1 portakal(dilimlenmiş),1 limon(dilimlenmiş), 1 elma(doğranmış)"),
];