import 'package:cocktail_app/models/model.dart';

List<ProductModel> greenSmoothies = [
  ProductModel(
      id: 1000,
      name: "Ananas-Greyfurt\nDetoks Smoothie",
      img: "assets/images/smoothies_img/green_smoothies_img/ananas_greyfurt_smoothie.jpg",
      description: "Smoothie - İki kişilik",
      firstStep: "Hindistan cevizi suyu, ananas, ıspanak, greyfurt ve diğer meyve suları, zencefil ve buzu bir karıştırıcıda birleştirin.",
      secondStep: "Pürüzsüz ve köpüklü olana kadar püre haline getirin.",
      ingredient: "1 su bardağı hindistan cevizi suyu,1 su bardağı dondurulmuş doğranmış ananas,1 su bardağı ıspanak,1 küçük greyfurt-sıkılmış meyve suyu,Yarım çay kaşığı rendelenmiş taze zencefil,1 bardak buz"),
  ProductModel(
      id: 1001,
      name: "Çilek Muz Yeşil Smoothie",
      img: "assets/images/smoothies_img/green_smoothies_img/strawberry_banana.jpg",
      description: "Smoothie",
      firstStep: "Muz, ıspanak, yoğurt, süt, çilek ve keten tohumunu bir blenderde pürüzsüz hale gelinceye kadar püre haline getirin.",
      secondStep: "Bardağı dilediğiniz gibi süsleyin. Afiyet olsun.",
      ingredient: "1 orta boy muz,1 su bardağı ıspanak,Yarım bardak az yağlı sade yoğurt,Yarım su bardağı yağsız süt,6 dondurulmuş çilek,1 yemek kaşığı keten tohumu"),
  ProductModel(
      id: 1002,
      name: "Ispanak-Muzlu Smoothie",
      img: "assets/images/smoothies_img/green_smoothies_img/peanut_banana.jpg",
      description: "Smoothie",
      firstStep: "Bir karıştırıcıya kefir, fıstık ezmesi, ıspanak, muz ve bal (kullanılıyorsa) ekleyin.",
      secondStep: "İyice birleşene kadar orta-düşük hızda, gerektiği kadar karıştırın. Afiyet olsun.",
      ingredient: "1 su bardağı sade kefir,1 yemek kaşığı fıstık ezmesi,1 bardak ıspanak,1 dondurulmuş muz,1 yemek kaşığı bal (İsteğe bağlı)"),
  ProductModel(
      id: 1003,
      name: "Mango ve Lahana Smoothie",
      img: "assets/images/smoothies_img/green_smoothies_img/mango_kale.jpg",
      description: "Smoothie",
      firstStep: "Bir karıştırıcıya lahana, mango, muz ve portakal suyunu ekleyin.",
      secondStep: "Birkaç buz küpü ile bir rocks (düşük balon) bardağına süzün. Bir portakal kabuğu dilimini bardağın kenarına süslemek için kullanabilirsiniz.",
      ingredient: "1 su bardağı lahana,1 bardak dondurulmuş mango parçaları,1 küçük dilimlenmiş muz,1 su bardağı taze portakal suyu"),
  ProductModel(
      id: 1004,
      name: "Yeşil Çay Smoothie",
      img: "assets/images/smoothies_img/green_smoothies_img/tea_smoothie.jpg",
      description: "Smoothie - İki kişilik",
      firstStep: "Üzüm, ıspanak, yeşil çay, avokado ve balı bir karıştırıcıda birleştirin; Pürüzsüz olana kadar karıştır. Servis yapın.",
      secondStep: "İpucu: Daha yoğun yeşil çay tadı almak için iki kat fazla çay (veya iki poşet çay) kullanın, ancak fazla demlemeyin. Yeşil çay 3 dakikadan fazla demlenmemelidir; fazla demlemek çaya acı bir tat verecektir.",
      ingredient: "3 su bardağı dondurulmuş beyaz üzüm,2 bardak ıspanak,1-1/2 bardak soğutulmuş yeşil çay,1 orta boy olgun avokado,2 çay kaşığı bal"),
  ProductModel(
      id: 1005,
      name: "Ananas - Ispanaklı Smoothie",
      img: "assets/images/smoothies_img/green_smoothies_img/ananas_ıspanak.jpg",
      description: "Smoothie",
      firstStep: "Ananas suyunu ve suyu bir karıştırıcıda birleştirin, ardından ıspanak, mango ve ananası ekleyin.",
      secondStep: "Pürüzsüz olana kadar püre haline getirin.",
      ingredient: "1/4 bardak ananas suyu,1/4 bardak su,2 su bardağı ıspanak,1/2 bardak dondurulmuş mango parçaları,1/2 bardak dondurulmuş ananas parçaları"),
  ProductModel(
      id: 1006,
      name: "Kivi meyveli smoothie",
      img: "assets/images/smoothies_img/green_smoothies_img/kiwi_smoothie.jpg",
      description: "Smoothie - 2-3 kişilik",
      firstStep: "Muzu ve mangoyu doğrayın ardından tüm malzemeleri blendera koyun",
      secondStep: "Pürüzsüz hale gelinceye kadar çırpın, ardından 2 uzun bardağa dökün.",
      ingredient: "3 soyulmuş kivi,1 mango,500 ml ananas suyu,1 muz"),
  ProductModel(
      id: 1007,
      name: "Gökkuşağı Smoothie",
      img: "assets/images/smoothies_img/green_smoothies_img/rainbow_smoothie.jpg",
      description: "Smoothie - İki kişilik",
      firstStep: "100 gr karışık meyve (çilek, ahududu ve yaban mersini olabilir), ıspanak, avokado, mango, elma ve badem sütünü bir karıştırıcıya koyun.",
      secondStep: "Pürüzsüz ve kalın bir kıvama gelinceye kadar karıştırın. İki büyük boy bardağa paylaştırın ve üzerine ejder meyvesi ve meyveleri ekleyin.",
      ingredient: "50 gr ıspanak,1 avokado-yarıya bölünmüş,1 olgun mango-parçalara bölünmüş,1 elma-parçalara bölünmüş,200 ml badem sütü,1 ejderha meyvesi-parçalara bölünmüş,100 gr karışık meyve "),
  ProductModel(
      id: 1008,
      name: "Lahana, limon yeşil smoothie",
      img: "assets/images/smoothies_img/green_smoothies_img/lime_kale.jpg",
      description: "Smoothie - 4 kişilik",
      firstStep: "Misket limonu, elma, salatalık, lahana, ıspanak, zencefil ve hindistancevizi suyunu bir karıştırıcıya koyun ve pürüzsüz hale gelinceye kadar karıştırın.",
      secondStep: "Servis bardaklarına paylaştırıp hemen servis yapın.",
      ingredient: "1 limon (iri doğranmış),1 elma (soyulmuş-iri doğranmış),1 salatalık (iri doğranmış),1/2 demet lahana (iri doğranmış),40 gr ıspanak yaprağı,1 çay kaşığı rendelenmiş zencefil,400 ml hindistan cevizi suyu"),
  ProductModel(
      id: 1009,
      name: "Yeşil Sebze Smoothie",
      img: "assets/images/smoothies_img/green_smoothies_img/green_vegie.jpg",
      description: "Smoothie - İki kişilik",
      firstStep: "Tüm malzemeleri blendera yüksek hızda koyun ve pürüzsüz hale gelinceye kadar karıştırın.",
      secondStep: "2 uzun bardağa bölün. Servis etmek için üzerine taze nane serpin.",
      ingredient: "1 su bardağı ıspanak (doğranmış),1 su bardağı kıyılmış lahana (doğranmış),1/2 bardak kereviz (doğranmış),1/2 çay kaşığı tarçın,1 yeşil elma (doğranmış),1 armut (doğranmış),2 büyük muz (dondurulmuş-doğranmış),2 su bardağı su,Servis etmek için taze nane"),
  // ProductModel(
  //     id: 1010,
  //     name: "",
  //     img: "assets/images/smoothies_img/green_smoothies_img/mango_kale.jpg",
  //     description: "Alkolsüz",
  //     firstStep: "",
  //     secondStep: "",
  //     ingredient: ""),
  // ProductModel(
  //     id: 1011,
  //     name: "",
  //     img: "assets/images/smoothies_img/green_smoothies_img/mango_kale.jpg",
  //     description: "Alkolsüz",
  //     firstStep: "",
  //     secondStep: "",
  //     ingredient: ""),
];

List<ProductModel> proteinSmoothies = [
  ProductModel(
      id: 1100,
      name: "Muz badem proteini",
      img: "assets/images/smoothies_img/protein_smoothies_img/banana_almond_protein.jpg",
      description: "21 gram protein sağlayarak kaslarınızdaki mikro yırtıkların onarılmasına yardımcı olarak bir sonraki spor salonu seansınıza hazırlanmanıza yardımcı olur.\n- 329 kalori, 21 gr protein, 26 gr karbonhidrat, 17 gr yağ",
      firstStep: "Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "Yarım su bardağı hindistan cevizi suyu,Yarım bardak sade yoğurt,3 yemek kaşığı badem ezmesi,1 kaşık peynir altı suyu protein tozu,1 dondurulmuş muz,1 bardak buz"),
  ProductModel(
      id: 1101,
      name: "Protein Power Smoothie",
      img: "assets/images/smoothies_img/protein_smoothies_img/protein_power.jpg",
      description: "Vücudunuza ciddi miktarda protein sağlamak için bu meyveli smoothieyi içebilirsiniz.\n- 284 kalori, 27 gr protein, 42 gr karbonhidrat, 2 gr yağ",
      firstStep: "Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "¾ su bardağı yağsız süt,Yarım olgun muz,Yarım bardak dondurulmuş ahududu,Yarım bardak dondurulmuş yaban mersini,1 kaşık vanilya peynir altı suyu protein tozu,5 buz küpü"),
  ProductModel(
      id: 1102,
      name: "Very Berry Super Shake",
      img: "assets/images/smoothies_img/protein_smoothies_img/very_berry.jpg",
      description: "Bu shake protein, lif, bitkisel besinler ve probiyotiklerle doludur. Kahvaltı, öğle yemeği veya akşam yemeği olabilir.\n- 500 kalori, 57 gr protein, 54 gr karbonhidrat, 11 gr yağ",
      firstStep: "Kırmızı meyvelerden çilek, ahududu, kiraz, yaban mesini vb. olabilir. Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "350 ml su,1 bardak ıspanak,2 su bardağı dondurulmuş kırmızı meyve,1/2 bardak sade az yağlı yoğurt,2 kaşık vanilya protein tozu,1 yemek kaşığı ceviz,1 yemek kaşığı öğütülmüş keten tohumu"),
  ProductModel(
      id: 1103,
      name: "Çikolata, Fıstık Ezmesi ve Muzlu Shake",
      img: "assets/images/smoothies_img/protein_smoothies_img/chocolate_banana_peanut.jpg",
      description: "Bu lezzetli çikolata ve fıstık ezmeli karışımın içinde bir fincan ıspanağın saklandığını asla tahmin edemezsiniz.\n- 585 kalori, 59 gr protein, 22 gr yağ, 38 gr karbonhidrat, 8 gr lif",
      firstStep: "Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "350 ml su-süt veya yoğurt,2 yemek kaşığı çikolata aromalı protein tozu,1 muz,1 fincan ıspanak,2 yemek kaşığı fıstık ezmesi,1 yemek kaşığı kakao"),
  ProductModel(
      id: 1104,
      name: "Çilekli Muzlu Smoothie",
      img: "assets/images/smoothies_img/protein_smoothies_img/strawberry_banana.jpg",
      description: "Protein içeceğine öğütülmüş keten eklenmesinin size ekstra lif ve omega-3 yağları sağlayacağını söylemek isteriz.",
      firstStep: "Protein tozu vanilya veya çilekli olmalıdır.Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "350 ml su-süt veya yoğurt,2 kaşık protein tozu,1 muz,1 su bardağı dondurulmuş çilek,1 fincan ıspanak,2 yemek kaşığı keten tohumu"),
  ProductModel(
      id: 1105,
      name: "Çikolata Kirazlı Smoothie",
      img: "assets/images/smoothies_img/protein_smoothies_img/chocolate_cherry.jpg",
      description: "- 530 kalori, 56 gr protein, 13 gr yağ, 47 gr karbonhidrat, 9 gr lif",
      firstStep: "Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "350 ml su-süt veya yoğurt,2 yemek kaşığı çikolata aromalı protein tozu,2 bardak tatlı koyu kiraz, çekirdekleri çıkarılmış,1 fincan ıspanak,1 yemek kaşığı ceviz,1 yemek kaşığı öğütülmüş keten,1 yemek kaşığı kakao"),
  ProductModel(
      id: 1106,
      name: "Vanilyalı Balkabaklı Smoothie",
      img: "assets/images/smoothies_img/protein_smoothies_img/vanilla_pumpkin.jpg",
      description: "Balkabağının gözleriniz, cildiniz ve bağışıklık sisteminiz için iyi olan harika bir A Vitamini kaynağı olduğu söylenmektedir.\n- 535 kalori, 60 gr protein, 13 gr yağ, 45 gr karbonhidrat, 13 gr lif",
      firstStep: "Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "350 ml su-süt veya yoğurt,2 kaşık vanilyalı protein tozu,¾ bardak püresi kabak,1 yemek kaşığı ceviz,1 yemek kaşığı öğütülmüş keten,½ bardak yulaf,Tarçın ve vanilya özü,Gerektiği kadar buz"),
  ProductModel(
      id: 1107,
      name: "Yaban Mersinli Smoothie",
      img: "assets/images/smoothies_img/protein_smoothies_img/blueberry_breakfast.jpg",
      description: "Bu shake dengeli bir kahvaltının tanımı olabilir. Günün geri kalanında kendinizi daha tok hissetmenize yardımcı olacak 42 gramlık sağlıklı bir protein oranına sahip olduğunu söyleyebiliriz.\n- 536 kalori, 42 gr protein, 59 gr karbonhidrat, 12 gr fiber, 18 gr yağ",
      firstStep: "Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "1 bardak yaban mersini,Yarım muz,1 kaşık protein tozu,2 yemek kaşığı ceviz,2 yemek kaşığı yulaf,1 yemek kaşığı chia tohumu"),
  ProductModel(
      id: 1108,
      name: "The Green Monster Smoothie",
      img: "assets/images/smoothies_img/protein_smoothies_img/green_monster.jpg",
      description: "- 346 kalori, 9 gr protein, 12 gr yağ, 62 gr karbonhidrat",
      firstStep: "Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "230-290 ml su,2 sap lahana,1 bardak üzüm,Yarım bardak dondurulmuş mango parçaları,1 şerit limon kabuğu,Yarım avokado,Gerektiği kadar buz"),
  ProductModel(
      id: 1109,
      name: "Şeftali ve Protein Smoothie",
      img: "assets/images/smoothies_img/protein_smoothies_img/peach_smoothie.jpg",
      description: "Uzmanlar, antrenman sonrasında kasların büyümesine yardımcı olmak için en az 30 gram proteine ihtiyacınız olduğunu söylüyor. Bu karışımdaki 42 gram kolayca azalıyor.\n- 468 kalori, 42g protein, 40g karbonhidrat (6g fiber), 13g yağ",
      firstStep: "Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "2 şeftali,Yarım bardak sade yoğurt,3/4 bardak bardak tam yağlı süt,1/4 bardak nane,1 kaşık vanilya protein tozu"),
  ProductModel(
      id: 1110,
      name: "Yeşiller ile Berry Smoothie",
      img: "assets/images/smoothies_img/protein_smoothies_img/berry_blast_greens.jpg",
      description: "Yeşilliklerinizi yemekte zorlanıyorsanız içebilirsiniz.\n- Porsiyon başına: 290 kalori, 31g protein, 31g karbonhidrat (6g fiber), 7g yağ",
      firstStep: "Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "1 kaşık vanilya veya çilekli protein tozu,1 bardak ıspanak,1 su bardağı dondurulmuş karışık meyve,180 ila 350 ml arası süt veya su"),
  ProductModel(
      id: 1111,
      name: "Tropilkal Smoothie",
      img: "assets/images/smoothies_img/protein_smoothies_img/tropical_protein.jpg",
      description: "- Porsiyon başına: 525 kalori, 58g protein, 46g karbonhidrat (9g fiber), 12g yağ",
      firstStep: "Tüm malzemeleri blendera koyup karıştırın.",
      secondStep: "Protein Smoothie'niz hazır! Afiyet olsun.",
      ingredient: "1 bardak süt,2 kaşık vanilya protein tozu,Yarım muz,1 bardak ananas,1 bardak ıspanak,1 yemek kaşığı keten tohumu,2 yemek kaşığı hindistan cevizi gevreği,Yarım su bardağı yoğurt."),
];

List<ProductModel> yogurtSmoothies = [
  ProductModel(
      id: 1200,
      name: "Karpuz Yoğurt Smoothie",
      img: "assets/images/smoothies_img/yogurt_smoothies_img/watermelon_yogurt.jpg",
      description: "Hazırlanması 10 dakika süren bu canlı pembe kahvaltılık smoothie tarifini hazırlayın. Soğutulmuş karpuz ve yoğurtla yaz için idealdir.",
      firstStep: "Karpuz, ahududu ve limon suyunu 4 buz küpüyle birlikte blendera koyun ve pürüzsüz hale gelinceye kadar karıştırın.",
      secondStep: "Üzerine yoğurt gezdirerek servis yapın.",
      ingredient: "1 su bardağı dondurulmuş karpuz,6 adet dondurulmuş ahududu,1 limon-suyu sıkılmış,1/4 bardak yoğurt"),
  ProductModel(
      id: 1201,
      name: "Mango Yoğurt Smoothie",
      img: "assets/images/smoothies_img/yogurt_smoothies_img/mango_yogurt.jpg",
      description: "Smoothie",
      firstStep: "Yoğurt, mango, hindistan cevizi sütü ve balı bir karıştırıcıya koyun ve 20 saniye boyunca pürüzsüz ve birleşene kadar karıştırın.",
      secondStep: "Hindistan cevizi ile süslenmiş soğutulmuş bardaklarda servis yapın.",
      ingredient: "2 bardak sade yoğurt,500g dondurulmuş mango parçaları,1 bardak hindistan cevizi sütü,2 yemek kaşığı bal,1/3 bardak hindistan cevizi gevreği"),
  ProductModel(
      id: 1202,
      name: "Mango Lime Smoothie",
      img: "assets/images/smoothies_img/yogurt_smoothies_img/mango_lime_yogurt.jpg",
      description: "Smoothie",
      firstStep: "Mango, muz, portakal suyu, yoğurt ve limon suyunu 6 buz küpüyle bir karıştırıcıda birleştirin.",
      secondStep: "Pürüzsüz olana kadar işlem yapın. Hemen servis yapın.",
      ingredient: "2 olgun mango, soyulmuş,2 muz,1 su bardağı portakal suyu,60 gr sade yoğurt2 yemek kaşığı limon suyu"),
  ProductModel(
      id: 1203,
      name: "Elma ve Muzlu Smoothie",
      img: "assets/images/smoothies_img/yogurt_smoothies_img/apple_banana_yogurt.jpg",
      description: "Smoothie",
      firstStep: "Tüm malzemeleri blendera koyun ve karıştırın. Buz eklemek onu daha kalın ve kremsi hale getirecektir.",
      secondStep: "Bir bardağa dökün ve üzerine biraz doğranmış elma ve tarçın serpin.",
      ingredient: "1 su bardağı badem sütü,1 elma,1 muz,Yarım çay kaşığı tarçın,1 yemek kaşığı yoğurt,1 çay kaşığı bal"),
  ProductModel(
      id: 1204,
      name: "Bircher Müsli Smoothie",
      img: "assets/images/smoothies_img/yogurt_smoothies_img/bircher_muesli.jpg",
      description: "Smoothie",
      firstStep: "Tüm malzemeleri bir kapta birleştirin. Örtün ve gece boyunca buzdolabında saklayın.",
      secondStep: "Karışımı bir karıştırıcıya aktarın. Tamamen pürüzsüz hale gelinceye kadar çırpın. Servis bardaklarına paylaştırıp muz, elma ve çilek ile servis yapın.",
      ingredient: "1 bardak süt,1 küçük elma,1 muz,4 çilek,1/4 çay kaşığı tarçın,1 yemek kaşığı chia tohumu,2 yemek kaşığı yulaf ezmesi,1/4 bardak yoğurt"),
  ProductModel(
      id: 1205,
      name: "Muzlu Kahvaltı Meyveli Smoothie",
      img: "assets/images/smoothies_img/yogurt_smoothies_img/banana_breakfast_yogurt.jpg",
      description: "Smoothie",
      firstStep: "Tüm malzemeleri blendera koyun ve pürüzsüz hale gelinceye kadar karıştırın.",
      secondStep: "Soğuk servis bardaklarına dökün.\n- İpucu: Doğranmış meyvelerinizi önceden dondurun veya smoothie'nizi daha da ferahlatıcı hale getirmek için ekstra buz ekleyin.",
      ingredient: "1 muz, doğranmış,Yarım bardak kırmızı meyveler,1 su bardağı badem sütü"),
  ProductModel(
      id: 1206,
      name: "Berry, Kefir ve Yulaflı Smoothie",
      img: "assets/images/smoothies_img/yogurt_smoothies_img/berry_kefir_yogurt.jpg",
      description: "Kefir, bu lif dolu smoothie'de bağırsakları güçlendiren bir maddedir.",
      firstStep: "Tüm malzemeleri yüksek güçlü bir karıştırıcıya ekleyin ve tamamen pürüzsüz hale gelinceye kadar karıştırın.",
      secondStep: "4 bardağa paylaştırıp servis yapın.",
      ingredient: "4 büyük muz(parçalara ayrılmış-donmuş),2 bardak kefir,150 gr dondurulmuş meyveler,80g yulaf,20 gr hurma"),
  ProductModel(
      id: 1207,
      name: "Çilek-Şeftali Smoothie",
      img: "assets/images/smoothies_img/yogurt_smoothies_img/strawberry_peach_yogurt.jpg",
      description: "Smoothie",
      firstStep: "Bir karıştırıcıya elma suyu, yoğurt, karnabahar pirinci, çilek, şeftali ve şekeri (kullanılıyorsa) ekleyin.",
      secondStep: "Pürüzsüz olana kadar karıştırın.",
      ingredient: "½ su bardağı elma suyu,¼ fincan az yağlı yoğurt,½ bardak dondurulmuş karnıbahar pirinci,½ bardak dondurulmuş çilek,½ bardak dondurulmuş şeftali,1 yemek kaşığı toz şeker(İsteğe bağlı)"),
  ProductModel(
      id: 1208,
      name: "Portakallı smoothie",
      img: "assets/images/smoothies_img/yogurt_smoothies_img/orange_yogurt.jpg",
      description: "Smoothie - 1 kişilik\nPorsiyon Başına Kalori: 388",
      firstStep: "Yaklaşık yarım portakalın kabuğunu rendeleyin. Soyulmuş portakalları, portakal kabuğu rendesini, muzu, yoğurdu, vanilyayı, balı ve buzu bir karıştırıcıya ekleyin.",
      secondStep: "Pürüzsüz olana kadar karıştırın. 1 gün kadar buzdolabında saklayın. Afiyet olsun.",
      ingredient: "2 soyulmuş portakal,Yarım yemek k. portakal kabuğu rendesi,1 muz,1/4 fincan yoğurt,Yarım çay kaşığı vanilya,1 yemek kaşığı bal,2 bardak buz"),
  ProductModel(
      id: 1209,
      name: "Çikolatalı Muzlu Smoothie",
      img: "assets/images/smoothies_img/yogurt_smoothies_img/chocolate_banana_yogurt.jpg",
      description: "Smoothie-2 kişilik\nPorsiyon Başına Kalori: 192",
      firstStep: "Muzu parçalara ayırarak tüm malzemeleri listelenen sıraya göre bir karıştırıcıya yerleştirin. Kremsi ve köpüklü olana kadar karıştırın, gerekirse durdurun ve kenarlarını kazıyın ve gerekirse biraz daha sıvı ekleyin.",
      secondStep: "Hemen servis yapın veya kapalı bir kavanozda buzdolabında 2 gün saklayabilirsiniz.",
      ingredient: "1/3 bardak süt,1/4 bardak yoğurt,2 orta boy muz,1 bardak buz,1/4 fincan kakao tozu,1.5 yemek kaşığı akçaağaç şurubu,Yarım çay kaşığı vanilya,1 yemek k. fıstık ezmesi(isteğe bağlı)"),
];